### ISSUE TITLE
StatisticTable() incorrect result_string included in table

### ISSUE THREAD

**Issue by jjb-hub** [remicorne/phd#88]
Compare the single histogram statistic with the one saved in the StatistcsTable they are not the same. 
HISTOGRAM for DA A agonist_antagonist:
<img width="1233" alt="Screenshot 2024-11-16 at 15 17 46" src="https://github.com/user-attachments/assets/19d86471-0667-4ac3-8490-37e838a9ace6">
STATISTICSTABLE:
<img width="1075" alt="Screenshot 2024-11-16 at 15 18 30" src="https://github.com/user-attachments/assets/c559bede-0cb6-4031-8116-c8c40d7de985">

**Comment by remicorne** [comment]
@jjb-hub Use both picture and code snippets in the future, its a pain for me to recopy code

**Comment by jjb-hub** [comment]
solved HUMAN Error
